### ISSUE TITLE
Create a new instance of sphinx-base to give @kd-ods somewhere to work

### ISSUE THREAD

**Issue by robredpath** [openownership/data-standard#60]
- Same repo as current docs
- Create new docs on a new branch, with example of first couple of headings of spec 
- @timgdavies to skeleton docs from there 
- Option to remove or keep current docs

**Comment by Bjwebb** [comment]
@timgdavies I think https://github.com/openownership/data-standard/tree/60-refactor-docs has what you need to get started now. This builds to https://beneficial-ownership-data-standard.readthedocs.io/en/60-refactor-docs/ (readthedocs says build failed, but that's one of the non-html builds, which I can fix later).

I added some new directives https://github.com/openownership/data-standard/commit/76a9eb49534d148db1a02447d3b011548077e493, see them at https://beneficial-ownership-data-standard.readthedocs.io/en/60-refactor-docs/schema.html#statement-groups

**Comment by kindly** [comment]
@kd-ods just checking you have seen this.

**Comment by kd-ods** [comment]
Thanks @kindly - I hadn't seen this. Have been writing copy, so will start working on the new refactor-docs branch next week I hope. I'll prob need your help @Bjwebb to get up and running with this. Thanks for setting it up!

**Comment by kd-ods** [comment]
@timgdavies @Bjwebb I'm tracking this new branch and have checked it out. I went to try and build the docs locally and I'm having a problem, though. On installing requirements.txt, I get the following error (after various packages have already successfully installed). Any ideas?

`Complete output from command /home/kadie/code/bods/.ve/bin/python3 -c "import setuptools, tokenize;__file__='/home/kadie/code/bods/.ve/src/sphinxcontrib-jsonschema/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/kadie/code/bods/.ve/lib/python3.5/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/home/kadie/code/bods/.ve/lib/python3.5/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/kadie/code/bods/.ve/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/home/kadie/code/bods/.ve/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/home/kadie/code/bods/.ve/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/home/kadie/code/bods/.ve/lib/python3.5/site-packages/pkg_resources/__init__.py", line 956, in subscribe
        callback(dist)
      File "/home/kadie/code/bods/.ve/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/home/kadie/code/bods/.ve/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2515, in activate
        declare_namespace(pkg)
      File "/home/kadie/code/bods/.ve/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/home/kadie/code/bods/.ve/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/home/kadie/code/bods/.ve/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    
    ----------------------------------------
Command "/home/kadie/code/bods/.ve/bin/python3 -c "import setuptools, tokenize;__file__='/home/kadie/code/bods/.ve/src/sphinxcontrib-jsonschema/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /home/kadie/code/bods/.ve/src/sphinxcontrib-jsonschema/
`

**Comment by kd-ods** [comment]
^ ignore. Sorry - I've just seen that I need to install pre-requirements.txt first.

**Comment by timgdavies** [comment]
Pretty sure this was done.
